# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20171112_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
