# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_discussion_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
